[phases.install]
nixPkgs = ["python311", "postgresql"]

[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn sapere.wsgi:application --bind 0.0.0.0:$PORT"