[phases.setup]
nixPkgs = ['nodejs_20', 'openssl']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npx prisma generate && npx prisma db push && npm run start:railway'
